spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: anti-gaspi
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${CUSTOMCONNSTR_BDD_URL}
    username: ${CUSTOMCONNSTR_BDD_USER}
    password: ${CUSTOMCONNSTR_BDD_PASSWORD}
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway
senGrid:
  enabled: true
  send-grid-api-key: SENDGRID_API_KEY
sendgrid:
  api-key: ${CUSTOMCONNSTR_SENDGRID_KEY}
  url: ${CUSTOMCONNSTR_SENDGRID_URL}
server:
  port: 8081
front-url: ${CUSTOMCONNSTR_FRONT_URL}
